### ISSUE TITLE
Normalize TimeRange by weeks

### ISSUE THREAD

**Issue by boriskogan81** [esnet/pond#100]
I'm trying to build charts showing crop development over a year, between several seasons. 

I have different timeseries, of course, from the different seasons.

I'd like to stack the charts one on top of the other, and normalize them to weeks, so that the x-axis goes from 0-52 weeks, but you can still see the date of a particular event or measurement when hovering over it. 

I'd renormalize the initial data to weeks, but am afraid that would not meet the second requirement.

How should I build the TimeRange?

**Comment by pjm17971** [comment]
This isn't possible with this library. Sorry.
