### ISSUE TITLE
TimeSeries#min() for a list of IndexedEvent objects.

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/pond#106]
Hi there,

How can I specify the first argument (fieldPath) of TimeSeries#min( ) method for the following data (a list of IndexedEvent) so that I can retrieve the min value of the second element of the score array.

```
   const events = _.map(myData, (d) => {
      return new IndexedEvent(
        d.index,
        {
          score: [
            d.first,
            d.second,   <---- I would like to retrieve the min value of this element.
            d.third,
            d.fourth,
          ]
        },
        false
      );
    });
    const ts = new TimeSeries({ name:'events', collection: new Collection(events)});
    const min = ts.min(????);
```
Or is it impossible to use the min method of TimeSeries for IndexedEvent ??

Cheers

**Comment by pjm17971** [comment]
If you have a series like this:
```js
const series = new Pond.TimeSeries({
  name: "series",
  columns: ["index", "score"],
  points: [
      ["1d-1234", [1, 6, 3]],
      ["1d-1235", [4, 5, 6]],
      ["1d-1236", [7, 8, 9]]
  ]
});
```

you should be able to use dot path notation to specify the deep field. Assuming what you want is to have the min in this case of 6, 5 and 7:

```js
series.min("score.1") // 5
```

**Comment by tech-a-go-go** [comment]
Wow, it worked well !!

I knew I can specify a dot path notation but I thought it only works for an object but an array.

Thank you so much.
