### ISSUE TITLE
Pond and InfluxDB

### ISSUE THREAD

**Issue by dobicz** [esnet/pond#111]
Hello,

I have a REST server that returns data in Metric queries from InfluxDB, in those queries I already have the metric / metric summation and the time interval, I would like to know how to transform this into a Pond timeseries and then use it in React Timeseries Charts ESnet.

Could someone post an example?

**Comment by pjm17971** [comment]
You just need it in this format:
```
{
   name: "seriesname",
   columns: ["time", "metric1", "metric2", ...],
   points: [
      [t1, m1, m2],
      [t2, m1, m2],
      ...
   ]
}
```

In fact, this used to be influxdbs format.
Then you can pass that object into a TimeSeries object.
