### ISSUE TITLE
Aggregate Functions Break If Period in Column Name

### ISSUE THREAD

**Issue by abramjstamper** [esnet/pond#127]
I had the column name of `'com.example.myapp'`. When I attempt to do a min/max on it, I get undefined back from the function. If I change `'com.example.myapp'` to `'myapp'` everything works as expected. I'm using version `0.8.9` of Pond with Node `v10.11.0`. Any ideas as to why that might be happening?

**Comment by sartaj10** [comment]
Periods in Pond represent a path to deep data, so you can't do that. Sorry, that's pretty low level to how it works.

**Comment by abramjstamper** [comment]
Thanks for the quick response. Closing the issue.
