### ISSUE TITLE
TimeSeries constructor fails with: Cannot read property 'isChronological' of null

### ISSUE THREAD

**Issue by spinlock99** [esnet/pond#129]
I'm evaluating `react-timeseise-chart` and `pond` and I can't seem to construct a `TimeSeries` to pass to `react-timeseries-charts`. When I try to construct a `TimeSeries` it fails with the error:

```
Uncaught TypeError: Cannot read property 'isChronological' of null
    at new TimeSeries (timeseries.js:302)
```

I've tried copying the [Baseline Demo](http://software.es.net/react-timeseries-charts/#/example/baselines) but that is giving me the same error. I've created the following minimal example of this error here:

```
import { TimeSeries } from "pondjs";

const usdVsEuro = require("./usd_vs_euro.json");
points = usdVsEuro.widget[0].data.reverse();

console.table(points);

const timeseries = new TimeSeries({
  "name": "USD_vs_EURO",
  "column": ["time", "value"],
  points
});
```

Any help would be greatly appreciated.

Thanks!

Note: I inlined the usd vs euro json to make my example simpler. I reverted to the original here so save space.

**Comment by sartaj10** [comment]
@spinlock99 
Hi, just to be sure, what versions of pond and react-timeseries-charts library are you using?

**Comment by spinlock99** [comment]
So, I figured this out as soon as I hit submit. If you look in the `TimeSeries` constructor, I'm passing an object with the key `column` instead of `columns`. Using the right keys fixes the issue.

Sorry about that.

P.S. I am using 0.8.9 to be consistent with `react-timeseries-charts`

**Comment by spinlock99** [comment]
This sounds like a great suggestion to me. Even just making the error message more precise would be a big help.

I haven't looked at the source (and I'm using an old version) but let me know if you'd like any help with this.
