### ISSUE TITLE
Documentation of getIndexString

### ISSUE THREAD

**Issue by gajus** [esnet/pond#137]
https://software.es.net/react-timeseries-charts/#/example/barchart mentions `getIndexString`, but I cannot find documentation for this function in Pond repository.

**Comment by MGough** [comment]
I'm slightly late to respond to this one, but it might be useful for anyone else that can't find this.

It's [here](https://esnet-pondjs.appspot.com/#/Index.getIndexString)! In the documentation for version 0.8

If that link isn't working, try this one, it's on this page: https://esnet-pondjs.appspot.com/#/index
