### ISSUE TITLE
A time-series database?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [esnet/pond#187]
I just wanted to know which database works best with this package or if there is anything you would recommend. Do you use any? Or do you have your own implementation?

**Comment by pjm17971** [comment]
We have our own system, which is built on top of Bigtable on Google Cloud. Our APIs that read from Bigtable convert the result of Bigtable queries to Pond TImeSeries format and return those. Our front end rehydrates the data into a TimeSeries and either processes it further using Pond, or passes it to the react-timeseries-charts code for rendering.
