### ISSUE TITLE
Fill function

### ISSUE THREAD

**Issue by pjm17971** [esnet/pond#32]
This is the case where you have a raw TimeSeries and you want to heal missing values. I think you want to be able to do a couple of things:

 * Filter out events with missing values in a fieldSpec - this is just a specialized filter operation
 * Replace missing values with a new value

In the case of the second function, probably `fill()`, there's several ways to replace missing values. We need to decide what the minimum set is to be useful to us, initially. Possibilities are:

 * fill with 0
 * fill with previous non-missing value (pad)
 * interpolate between non-missing values, based on timestamp

For each of these it would be useful to supply a limit. A limit of 2 would fill two missing values only. This is because we often want to patch small holes in TimeSeries, but if there's a substantial hole it makes sense sometimes (e.g. visualization), to keep it as missing data. If we missed an hour of data it should show that.

Note: this is being implemented in PyPond first.

**Comment by jdugan1024** [comment]
@pjm17971 i think this is done, right?

**Comment by pjm17971** [comment]
No, it's not ported to pond.js yet, but should be by sept.

**Comment by pjm17971** [comment]
Fill is now checked into the version branch.
