### ISSUE TITLE
Bulletproof pipeline ops on empty series

### ISSUE THREAD

**Issue by montegoode** [esnet/pond#36]
Pipeline operations on empty `TimeSeries` will cause bad returns from `Pipeline.to_keyed_collections()` which will result in code wipeouts.

Corollary change to python code base:

https://github.com/esnet/pypond/commit/113cceb0b2d8b18b48ac189659d8d9fb36b0f4f8

**Comment by montegoode** [comment]
Some relevant notes from Slack:

As far as I can tell, there are no significant downstream problems with the empty `_type` attr. The only thing I can really find is that if you call `.to_json()` on that new empty `TimeSeries` you’re going to get some very bare bones output:
```
{"utc": true, "points": [], "name": "Sensor values", "columns": []}
```
The columns list can’t be built because 1) the `_type` is invalid and 2) there are no data.

It potentially impacts `Collection.at()` as well, but at least in the python version, type being None still won’t impact anything because since the series is empty, trying to index the empty event list it will fuck up first:

```
        try:
            return self._type(self._event_list[pos])
        except IndexError:
            raise CollectionException('invalid index given to at()')
```
I would say that the undefined event is a pretty safe change.

It isn’t about returning a good object, it’s just so code doesn’t blow up when people manipulate an empty time series and not hunting down a bunch of places in the code where this could manifest and explode.

**Comment by pjm17971** [comment]
These changes are rolled into the v0.7 branch now.
