### ISSUE TITLE
Chronological error in TimeSeries constructor

### ISSUE THREAD

**Issue by pjm17971** [esnet/pond#41]
We started to enforce that events passed to the TimeSeries constructor be chronological. This is important as operations on a TimeSeries sometimes depend on the events being in order. However, it seems there are ways for this to happen internally. Those operations should always make sure that their collections are in order.

A possible alternative is to just check if the events are in order and if not, sort them. This would be the least intrusive approach, but might lead to slow user code.

**Comment by pjm17971** [comment]
@jdugan1024 if you can reproduce the way you got this to happen, document here and I'll figure out how it got into that situation. For the time being, the pond/rename-column branch has the warn and sort change in it.

**Comment by pjm17971** [comment]
I fixed an issue where I think the merge code (which the TimeSeriesList* functions use). It basically just builds a map of timestamps to an array of stuff, that it then reduces. For one, I suppose those timestamp keys aren't really guaranteed to come out in order. For another, if the timeseries you add don't have their begin times in order, the keys will go into the map out of order. Here's a fix:
https://github.com/esnet/pond/commit/e5a1d6b381835c89c18b5e2adf42050398228ee9

**Comment by pjm17971** [comment]
Fixed in 0.6.1 and 0.7.1

**Comment by shahzeb61518** [comment]
getting in 0.16.1
