### ISSUE TITLE
Add typescript definitions d.ts file? [enhancement] 

### ISSUE THREAD

**Issue by siavelis** [esnet/pond#54]
pondjs should have .d.ts files distributed along with package.json

**Comment by dcworldwide** [comment]
This would be a nice addition.

**Comment by dcworldwide** [comment]
@siavelis Do you know how to get this started?

**Comment by siavelis** [comment]
Yes I know. I forked the repo and created a branch called 'typescript-declarations-#54'. I made an early implementation of the declarations file and updated package.json, so npm knows that this package provides declarations. (commit id ae621204abd64539d857d8cd763a26651d30461b)

Documentation and fields we extracted from the website. So, any fields or types not documented will be missing (i will check for any missing field/type).

**Comment by dcworldwide** [comment]
Excellent work @siavelis . Looks like you've made great progress. Looking forward to using it.

**Comment by pjm17971** [comment]
FYI: #65.

If I get a bit further I'll make a check in a branch and let you guys know about it. I think there's clearly a few complications to making this work, but I'm hopeful it can be done without too much pain and the rewards are great.

**Comment by opavader** [comment]
@siavelis & @pjm17971 can you merge [siavelis/pond:typescript-declarations-#54](https://github.com/siavelis/pond/tree/typescript-declarations-%2354) into this main repo? Typedefs itself will be very useful to have while https://github.com/esnet/pond/issues/65 is in progress.

**Comment by pjm17971** [comment]
Sure, I can accept a PR that adds those definitions. @siavelis: are you able to make one?

**Comment by siavelis** [comment]
Sure! Here's https://github.com/esnet/pond/pull/70.
I added the tsconfig.json so you can test if there any compilation error in the .d.ts.
You can test by running: `npm install typescript@2.0` and then running `tsc`

**Comment by pjm17971** [comment]
I'll try to push a release out in the next couple of days. Thanks for these!

**Comment by pjm17971** [comment]
Now in v0.8.6.
