### ISSUE TITLE
event.js:721 Uncaught TypeError: reducer is not a function(…)

### ISSUE THREAD

**Issue by expaand** [esnet/pond#55]
This is in 0.6.1, when I try to use dailyRollup with avg or sum.
Is this fixed in 0.7.1 ?
Will 0.7.1 be submitted to npm?

Thanks.

**Comment by pjm17971** [comment]
Hi, I just republished it and it seems to show up ok. 0.7.1 could be downloaded before from npm, but for some reason npm didn't think that was the most recent version.
https://www.npmjs.com/package/pondjs
