### ISSUE TITLE
Cant use avg() aggregate functions

### ISSUE THREAD

**Issue by piyushgupta1** [esnet/pond#58]
When I try to use aggregate fucnction to reduce to timeSeries with  `TimeSeries.timeseriesListReduce` it fails at run time with error in library
`TypeError: this._type is not a constructor`

Trying to reduce multiple time Series with same time range and different values
```
const data = { name: label,
                        columns: ['time', 'value'],
                        events: [['timestamp','value'],
                                    [timestamp','value'], ....]};
allTimeSeries.push(new TimeSeries(data));
```

```
  const sums = TimeSeries.timeseriesListReduce({
                    seriesList: allTimeSeries,
                    reducer: avg(),
                    fieldSpec: ['value']
                });
```

Development Environment : @angular 2.4.3
IDE: Visual Studio code

**Comment by piyushgupta1** [comment]
```
  key: "at",
        value: function at(pos) {
            if (this._eventList.size > 0) {
                var event = new this._type(this._eventList.get(pos));
                return event;
            }
        }
```
break point of code

**Comment by pjm17971** [comment]
The short version is that you are reducing multiple events together, which can have many fields, so you need an event reduction function, not one of the simple ones. Anyway, bottom line is you need to use `Event.avg` rather than just `avg()`, as shown here:

```
const part1 = new TimeSeries({
    name: "part1",
    columns: ["time", "in", "out"],
    points: [
        [1400425951000, 1, 6],
        [1400425952000, 2, 7],
        [1400425953000, 3, 8],
        [1400425954000, 4, 9]
    ]
});
const part2 = new TimeSeries({
    name: "part2",
    columns: ["time", "in", "out"],
    points: [
        [1400425951000, 9, 1],
        [1400425952000, 7, 2],
        [1400425953000, 5, 3],
        [1400425954000, 3, 4]
    ]
});

const avgSeries = TimeSeries.timeseriesListReduce({
        name: "avg",
        seriesList: [part1, part2],
        fieldSpec: ["in", "out"],
        reducer: Event.avg
});
```

Hope this helps.

**Comment by pjm17971** [comment]
I've added further docs (for the next release) to clarify this, along with further tests. I've also wrapped this use of of `timeseriesListReduce()` in a new method `timeSeriesListAvg()`. That release will improve performance for these functions considerably as well.
