### ISSUE TITLE
Exposing more aggregate functions for merging timeseries

### ISSUE THREAD

**Issue by piyushgupta1** [esnet/pond#59]
We already have a way to reduce timeseries on a reducer function like this

```
 avgSeries = TimeSeries.timeseriesListReduce({
                        name: 'avg',
                        seriesList: allTimeSeries,
                        fieldSpec: ['value'],
                        reducer: Event.avg
                    });
```

But as i have looked in documentation and source code only two aggregate function are available in Event.js
1. Sum
2. Avg

It would be good idea if there was a way to expose more aggregate functions in merging timeSeries. Like in my use case i need min max and other aggregate func. 

If this cant be done in current implementation, I am also willing to contribute to this lib.

**Comment by pjm17971** [comment]
I can add this, it fits in with changes to that code in the next version.
