### ISSUE TITLE
Fill not filling in correctly

### ISSUE THREAD

**Issue by jonathanwoahn** [esnet/pond#64]
I'm super excited to have run across this library--I think it could potentially help me with a big issue I've been working on lately.

I have a large time series dataset that has lots of missing values, so I found your "fill" linear function to be particularly interesting. However, i'm having an issue where when it goes to fill in null values, I get results that look like this:

![postman 2017-02-16 11-00-03](https://cloud.githubusercontent.com/assets/1209449/23029059/4c4c5468-f437-11e6-81df-9ed785c0b581.png)

Have you seen this before? If so, any thoughts on what may be causing this? Or is this the desired behavior, and I'm missing something?

Thanks!

**Comment by pjm17971** [comment]
Do you have a sample of the original data (e.g. with timeseries.toString()) you can send me?

**Comment by jonathanwoahn** [comment]
Here's the timeseries.toString():

"{\"name\":\"temp\",\"utc\":true,\"columns\":[\"time\",\"rate\",\"lossReasonId\",\"activityId\",\"runningVa\",\"departmentId\",\"eventTypeId\",\"units\",\"shiftSessionId\",\"actorId\",\"sessionId\",\"actorSessionId\",\"shiftId\"],\"points\":[[1484456086000,null,null,null,null,1,6,null,null,\"74P\",\"8624E\",\"16207\",null],[1484456086000,120,null,47,0,1,1,0,null,null,\"8624E\",null,null],[1484456086000,null,null,null,null,1,6,null,null,\"51P\",\"8624E\",\"16206\",null],[1484456086000,null,null,null,null,1,6,null,null,\"36M\",\"8624E\",\"36M\",null],[1484458983000,120,null,47,3600,1,5,30,null,null,\"8624E\",null,null],[1484461733000,null,null,null,null,1,7,null,null,\"51P\",\"8624E\",\"16206\",null],[1484461742000,null,null,null,null,1,6,null,null,\"8P\",\"8624E\",\"16208\",null],[1484461746000,120,null,47,6240,1,5,22,null,null,\"8624E\",null,null],[1484465350000,120,null,47,9480,1,5,27,null,null,\"8624E\",null,null],[1484467664000,120,null,47,12240,1,5,23,null,null,\"8624E\",null,null],[1484467683000,120,null,47,12240,1,3,0,null,null,\"8624E\",null,null],[1484474359000,120,7,47,12240,1,4,0,null,null,\"8624E\",null,null],[1484474363000,120,null,47,12240,1,5,0,null,null,\"8624E\",null,null],[1484480362000,120,7,47,16200,1,5,33,null,null,\"8624E\",null,null],[1484480390000,120,null,47,16200,1,3,0,null,null,\"8624E\",null,null],[1484480396000,null,null,null,null,1,7,null,null,\"74P\",\"8624E\",\"16207\",null],[1484480399000,null,null,null,null,1,7,null,null,\"8P\",\"8624E\",\"16208\",null],[1484529593000,null,null,null,null,1,6,null,null,\"8P\",\"8624E\",\"16238\",null],[1484529604000,null,null,null,null,1,6,null,null,\"58P\",\"8624E\",\"16239\",null],[1484529607000,120,7,47,16200,1,4,0,null,null,\"8624E\",null,null],[1484529612000,120,null,47,16200,1,5,0,null,null,\"8624E\",null,null],[1484532203000,120,null,47,18840,1,5,22,null,null,\"8624E\",null,null],[1484535722000,120,null,47,22320,1,5,29,null,null,\"8624E\",null,null],[1484539034000,120,null,47,25560,1,5,27,null,null,\"8624E\",null,null],[1484542929000,null,null,null,null,1,7,null,null,\"58P\",\"8624E\",\"16239\",null],[1484542954000,null,null,null,null,1,6,null,null,\"104P\",\"8624E\",\"16245\",null],[1484542993000,120,null,47,30000,1,5,37,null,null,\"8624E\",null,null],[1484545462000,120,6,47,31080,1,5,9,null,null,\"8624E\",null,null],[1484545489000,120,null,47,31080,1,2,0,null,null,\"8624E\",null,null],[1484545489000,null,null,null,null,1,7,null,null,\"104P\",\"8624E\",\"16245\",null],[1484545489000,null,null,null,null,1,7,null,null,\"36M\",\"8624E\",\"36M\",null],[1484545489000,null,null,null,null,1,7,null,null,\"8P\",\"8624E\",\"16238\",null]]}"

And I'm running: 
			```
var columns = _.keys(events[0].toJSON());

			columns[0] = 'time';
			
			var data = {
				name: 'temp',
				columns: columns,
				points: points
			};

			var ts = new pond.TimeSeries(data);

			var filled = ts.fill({
				fieldSpec: ['runningVa'],
				method: 'linear'
			});

```

**Comment by pjm17971** [comment]
I gave it a try and I think I got reasonable results. Here's my code:
```
    const data = {
        name: "temp",
        utc: true,
        columns: [
            "time",
            "rate",
            "lossReasonId",
            "activityId",
            "runningVa",
            "departmentId",
            "eventTypeId",
            "units",
            "shiftSessionId",
            "actorId",
            "sessionId",
            "actorSessionId",
            "shiftId"
        ],
        points: [
            [
                1484456086000,
                null,
                null,
                null,
                null,
                1,
                6,
                null,
                null,
                "74P",
                "8624E",
                "16207",
                null
            ],
            [
                1484456086000,
                120,
                null,
                47,
                0,
                1,
                1,
                0,
                null,
                null,
                "8624E",
                null,
                null
            ],
            ....
            [
                1484545489000,
                null,
                null,
                null,
                null,
                1,
                7,
                null,
                null,
                "8P",
                "8624E",
                "16238",
                null
            ]
        ]
    };
    const ts = new TimeSeries(data);
    const filled = ts.fill({
        fieldSpec: ["runningVa"],
        method: "linear"
    });
    for (let i = 0; i < filled.size(); i++) {
        const before = ts.at(i);
        const after = filled.at(i);
        console.log(
            before.timestamp(),
            before.get("runningVa"),
            after.get("runningVa")
        );
    }
```

Result:
```
      2017-01-15T04:54:46.000Z null null
      2017-01-15T04:54:46.000Z 0 0
      2017-01-15T04:54:46.000Z null 0
      2017-01-15T04:54:46.000Z null 0
      2017-01-15T05:43:03.000Z 3600 3600
      2017-01-15T06:28:53.000Z null 6227.5787187839305
      2017-01-15T06:29:02.000Z null 6236.178067318133
      2017-01-15T06:29:06.000Z 6240 6240
      2017-01-15T07:29:10.000Z 9480 9480
      ....
```

**Comment by jonathanwoahn** [comment]
Ok, so your results align exactly with what my excel model calculated (which is awesome!). 

Also, when I look at the console, I'm getting the same results you have, however my response JSON is providing the results of what I saw earlier. Looks like it has something to do with my API - thanks for helping me pinpoint that!
