### ISSUE TITLE
Moving library to Typescript

### ISSUE THREAD

**Issue by pjm17971** [esnet/pond#65]
Rewrite the library in Typescript. 😺 

The main goal here would be type safety, which I think would be a great benefit in the case of Pond. We can also look into using generics for things like events and collections. As we try to narrow in on what 1.0 would look like, this should be part of that conversation.

We've done some initial investigation into this, and it wouldn't be especially easy to convert, and very likely would cause more serious API changes. But also the benefits seem huge, and productivity downstream of this code base would be greatly enhanced by proper code completion and type checking.

Code structures:
 - [X] Time type to replace 14127847483 or Date
 - [X] Period type to replace "30s" strings
 - [X] Indexes
 - [X] Utility functions
 - [X] Aggregation functions
 - [X] EventKey type, Time, TimeRange and Index base
 - [X] Events<EventKey>
 - [X] Collections<<Event<EventKey>>
 - [x] TImeSeries

Collection processing
 - [X] Batch processing framework
 - [X] Aggregation
 - [X] Alignment and rates
 - [x] Filling
 - [X] Collapsing
 - [x] Selector
 - [ ] Take n

Stream processing
 - [ ] Should this be supported going forward?
 - [X] Stream processing node graph framework
 - [X] Event-wise processing
 - [ ] Grouping
 - [x] Windowing

Project:
 - [x] Transpile setup
 - [x] Generate website API docs from Typescript (@sartaj10)
 - [X] Figure out Jest testing in Typescript
 - [x] Rebuild website

**Comment by opavader** [comment]
@pjm17971 This will be a really great enhancement & worthwhile effort. 
This library is exactly what I have often try to achieve using [crossfilter](https://github.com/square/crossfilter). Given its usefulness for me I will be very much willing to help in any way possible (I have decent enough experience with typescript, webpack etc).

**Comment by pjm17971** [comment]
@opavader thanks for the comment. I'm glad you like it.

I've pretty much decided that the way forward for this library is to move it to typescript and that is actually making decent progress. (That work is actually in a different repo). The main thing has been the use of generics for events and collections and generally stricter typing, but I'm past most of that now.

Let me get a little further with it and I'll let you know here if you can help.

Thanks again.

**Comment by pjm17971** [comment]
For anyone tracking this item, this is definitely in progress. I've updated the above check list on June 11, 2017. There's several processors still to port (processors are setup so that a collection can flatMap over them now), the TimeSeries wrapper on top of a Collection (which does the heavy lifting), and figuring out to what extent to support streaming style pipelines (which we no longer use). In addition @sartaj10 is working on typescript docs generation for this project so we can put a new website together that looks roughly like immuatble.js in its type descriptions. Then we need to port react-timeseries-charts to use it. But progress.

**Comment by pjm17971** [comment]
This was updated July 23, 2017, within the typescript branch of this repo. That repo now fully reflects the current state of this typescript rewrite. Basically all previous tests pass, or there is some way to rewrite the code to get the same result (with a few exceptions). There's still a bunch of cleanup to do to get an alpha version of this up on npm, because some things broke when it got moved and the website/docs aren't quite there yet, and there's still a handful of type errors, but it's getting a lot closer now. Most of those problems should be resolved this week.

**Comment by pjm17971** [comment]
npm install pondjs@alpha should get you a full typescript version of pond. For the moment you can’t use this with react-timeseries-charts but that work is almost done. 

Sorry about the delay. For most of the summer tsc couldn’t build the project because it included immutable.js. That’s fixed since 2.5.3 so onwards and upwards!

**Comment by johnstuarthunter** [comment]
Any further idea on when there will be a version of react-timeseries-charts which will work with this new version of Pondjs?

**Comment by velsa** [comment]
We're getting close to two years on this. 
Any updates since 2018? :)

**Comment by pjm17971** [comment]
@velsa Sometimes that's how it goes. On the bright side, there are moves afoot to pick up this work.

**Comment by velsa** [comment]
Thanks for the answer and good luck!
Waiting patiently for the working typescript version of react-timeseries-charts and will be ready to pay/donate as soon as it's ready :)

**Comment by davegravy** [comment]
Also waiting patiently :) Any sign of resuming this work?
