### ISSUE TITLE
pond.js fails in uglify.js and wont work in Safari 9.0~ caused by new.target

### ISSUE THREAD

**Issue by yrokhlin** [esnet/pond#67]
These screenshots are all taken from the http://software.es.net/react-timeseries-charts/ domain

![image](https://cloud.githubusercontent.com/assets/6445303/23564586/76fef566-0018-11e7-8999-09e22bb6f7b5.png)

![image](https://cloud.githubusercontent.com/assets/6445303/23564621/9d20517c-0018-11e7-936b-787e542f1808.png)

The browser is Safari V9, this issue seems somewhat resolved in V10 however. 
![image](https://cloud.githubusercontent.com/assets/6445303/23564662/cb2a2c1e-0018-11e7-9a57-ea528e0269d4.png)

uglify fails as well in the same spots where `new.target` is used.

**Comment by yrokhlin** [comment]
I dug up some more info on `new.target` 

http://stackoverflow.com/questions/33360253/how-do-you-polyfill-javascript-es6-new-target

It could just be re-written in es5, but not sure of the proper solution here.

**Comment by pjm17971** [comment]
Maybe this:
```
        if (this.constructor.name === "Event") {
            throw new TypeError("Cannot construct Event instances directly");
        }
```
?

**Comment by pjm17971** [comment]
Hmm, ok, it doesn't make the test suite run noticeably slower, so I probably should have done it this way to begin with.  Will push a patch.

**Comment by yrokhlin** [comment]
Thanks, let me know if you need some one to test.

**Comment by pjm17971** [comment]
Sure, if you have a chance to try it, please do:
Branch is: 0.8.5-fix-new-target
I'll release it early next week if it looks good to you.

**Comment by pjm17971** [comment]
@yrokhlin did you ever manage to have a look at this change. I've been at a conference all week, so I've not touched this, but I can push it on Monday hopefully.

**Comment by mfonsen** [comment]
For me `0.8.5-fix-new-target` fixes the UglifyJS problem

When I upgraded pond from from 0.7.2 to 0.8.4 I got the following from UglifyJS:
`SyntaxError: Unexpected token: punc (.) [./~/pondjs/lib/lib/event.js:64,0]`

Thank you for a great project!

**Comment by pjm17971** [comment]
This should be in 0.8.5 now
