### ISSUE TITLE
pondjs not recognised after installing 

### ISSUE THREAD

**Issue by nikitagupta55** [esnet/pond#73]
I'm using Webstorm IDE and have created a create-react-app. I installed pondjs using:
 npm install pondjs --save ; it got installed and that's why I can see it in node-modules. 
But in my App.js when I'm trying to import it using : import { TimeSeries, TimeRange } from "pondjs";
this package is not recognised. Please help. I'm trying to solve this since long.

**Comment by pjm17971** [comment]
What do you mean that the package isn't recognized? I don't know about Webstorm IDE, but in a terminal this works:
```shell
> create-react-app test_install
> cd test_install
> npm install pondjs
```

Then I changed App.js to this:
```js
import React, { Component } from "react";
import { TimeRange } from "pondjs";

import "./App.css";

class App extends Component {
    render() {
        const oneHour = 60 * 60 * 1000;
        const now = new Date();
        const later = new Date(+now + oneHour);
        const timerange = new TimeRange(now, later);

        console.log(timerange);

        return (
            <div className="App">
                <div className="App-header">
                    <h2>
                        {timerange.toLocalString()}
                    </h2>
                </div>
            </div>
        );
    }
}
export default App;
```

This seems to work.

**Comment by nikitagupta55** [comment]
I also figured out that it's working using Terminal and Sublime Text. May be something is wrong with Webstorm IDE.
