### ISSUE TITLE
About TimeSeries.timeSeriesListReduce method

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/pond#74]
Hi there,

How can I use a reducer method for TimeSeries.timeSeriesListReduce ?

My code is as follows using the avg( ) method as a reducer method.

```
const TimeSeries = require('pondjs').TimeSeries;
const sum = require('pondjs').sum;
const max = require('pondjs').max;
const min = require('pondjs').min;
const avg = require('pondjs').avg;

const inTraffic = new TimeSeries({
    name: "in",
    columns: ["time", "in"],
    points: [
        [1400425947000, 52],
        [1400425947200, 51],
        [1400425948000, 18],
    ]
});

const outTraffic = new TimeSeries({
    name: "out",
    columns: ["time", "out"],
    points: [
        [1400425947000, 34],
        [1400425947500, 33],
        [1400425948000, 13],
    ]
});

const trafficSeries = TimeSeries.timeSeriesListReduce({
    name: "totals",
    seriesList: [inTraffic, outTraffic],
    reducer: avg(),       <===== avg( ) reducer
    fieldSpec: [ "in", "out"]
});

console.log(JSON.stringify(trafficSeries.toJSON(),null,2));
```

Here is the result.
```
{
  "name": "totals",
  "utc": true,
  "columns": [
    "time",
    "in",
    "out"
  ],
  "points": [
    [
      1400425947000,
      52,
      34
    ],
    [
      1400425947200,
      51,
      null
    ],
    [
      1400425947500,
      null,
      33
    ],
    [
      1400425948000,
      18,
      13
    ]
  ]
}
```
Even thought I specify min(), max(), avg() for a reducer method, the result didn't change at all. I got all same results.
So I'm wondering how the reducer method is used in TimeSeries.timeSeriesListReduce ?

Thanks a lot !

**Comment by pjm17971** [comment]
Yeah, it doesn't quite work that way. This function basically takes all the values of the same column (e.g. "in"), for the same time, and then applies the reducer function to those. It does that for just the columns in the fieldSpec.

```
const sumPart1 = {
    name: "part1",
    columns: ["time", "in", "out"],
    points: [
        [1400425951000, 1, 6],
        [1400425952000, 2, 7],
        [1400425953000, 3, 8],
        [1400425954000, 4, 9]
    ]
};
const sumPart2 = {
    name: "part2",
    columns: ["time", "in", "out"],
    points: [
        [1400425951000, 9, 1],
        [1400425952000, 7, 2],
        [1400425953000, 5, 3],
        [1400425954000, 3, 4]
    ]
};
```
Can then be reduced like so:
```
    const ts = TimeSeries.timeSeriesListReduce({
        name: "sum",
        seriesList: [part1, part2],
        reducer: sum(),
        fieldSpec: ["in", "out"]
    });
```

In this case the first point at 1400425951000 will be in=10 (9 + 1) and out=7 (6 + 1)

You might want to check out `TimeSeries.timeSeriesListMerge()` which would let you combine your "in" timeseries and your "out" timeseries together into a timeseries with both "in" and "out" in it. 

Then you could use `ts.collapse()` on that to reduce the "in" and "out" to a "total", or whatever you are trying to do.

**Comment by tech-a-go-go** [comment]
Oh, I see.
Now I know how it works.
Thank you so much !
