### ISSUE TITLE
Running total aggregator?

### ISSUE THREAD

**Issue by jonathanwoahn** [esnet/pond#77]
I'd love to create a "running total" pipeline aggregator, but the documentation on this is a little light. Two questions: a) Does this feature exist in the current iteration, or b) do you have suggestions on how I might tackle this within the current API?

Thanks!

**Comment by pjm17971** [comment]
By running total, do you mean sliding windows or some kind of accumulator that always increments a total with incoming events. See perhaps #49?

In either case though, there's no direct API support, though both are on the issue list. 

If you want a sliding window, you can make a `Collection` and in the case of a sliding window (say last n points), use `addEvent()` to grow the `Collection` and `slice()` to trim it. At each step, you can call `sum()` on the `Collection` to get the total. Direct support for sliding windows would be great, but it's not in the current version.

For the other case of the never ending accumulator (for streamed events), you can do something like it with a map function:
```
            // events are:
            //   TimeEvent(new Date("2015-04-22T03:30:00Z"), { in: 1, out: 2 }),
            //   TimeEvent(new Date("2015-04-22T03:31:00Z"), { in: 3, out: 4 }),
            //   TimeEvent(new Date("2015-04-22T03:32:00Z"), { in: 5, out: 6 })

            const accumulator = () => {
                let sum = 0;
                return v => {
                    sum += v;
                    return sum;
                };
            };

            const inAccum = accumulator();
            const outAccum = accumulator();

            const p = Pipeline()
                .from(stream)
                .map(e => {
                    return e.setData({ in: inAccum(e.get("in")), out: outAccum(e.get("out")) });
                })
                .to(EventOut, e => {
                    console.log(" -", e);   // "in" will be 1, 4, 9 ... 
                });

            stream.addEvent(events[0]);
            stream.addEvent(events[1]);
            stream.addEvent(events[2]);
```
