### ISSUE TITLE
Average aggregation

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/pond#81]
Hi,

I'm stuck on aggregation which needs to access multiple columns.
The average I want to calculate is not just an average but a weighted average.

Let's say I have the following data for TimeSeries.
```
[
 // DATE,       PRICE,   QUANTITY
 ['2017-01-01', $100,    150],
 ['2017-01-02', $200,    250],
 ['2017-01-03', $300,    100],
 ['2017-01-04', $100,    200],
 ....
]
```
If I set the window size to 3 days, I want the first result to be 190 as calculated as follows.
( $100 * 150 + $200 * 250 + $300 * 100) / ( 150 + 250 +100) = 190

It simply multiplies each price by the amount of quantity at that price, add them together, and then divide by the total number of quantity.

I've looked into pond's source code but it looked like the aggregation method takes only a single column so I'm stuck on accessing multiple columns.

If it's impossible to do with aggregation methods, any other ways you recommend ??

Thank you.

**Comment by pjm17971** [comment]
You can't do something like that directly with the aggregation helpers, you'll have to do some remapping on top of using pond to do the windowing. Something like this:

```javascript
const Pond = require("pondjs");
const _ = require("lodash");

const pts = [
    // DATE,       PRICE,   QUANTITY
    ["2017-01-01", 100, 150],
    ["2017-01-02", 200, 250],
    ["2017-01-03", 300, 100],
    ["2017-01-04", 100, 200]
];

const ts = new Pond.TimeSeries({
    name: "test",
    columns: ["time", "price", "quantity"],
    points: pts.map(p => [+new Date(p[0]), p[1], p[2]])
});

const output = _.map(ts.collectByFixedWindow({ windowSize: "3d" }), c => {
    const cc = c.map(e => new Pond.TimeEvent(e.timestamp(), {
                price_quantity: e.get("price") * e.get("quantity"),
                quantity: e.get("quantity")
            })
    );
    return cc.sum("price_quantity") / cc.sum("quantity");
});

console.log(output);
```

But note that the released version of pond only supports fixed (non-overlapping) windows, so if you're hoping to do a sliding window that won't work (yet). The actual windows (3 days) will be aligned to Jan 1, 1970. That may or may not be ok, depending on your use case.

The other thing is if you are streaming points like this, I think it's possible to do a similar thing, but I'd have to dig in and figure out how that would work again.

**Comment by tech-a-go-go** [comment]
okay, thank you so much !
