### ISSUE TITLE
Client side - Help wanted 

### ISSUE THREAD

**Issue by JF-Dumont** [esnet/pond#85]
Your lib look really very interesting and useful. 
I am currently on a project where I make graphs with dygraphs (my project is not in React land). The data comes from RRD or SQL databases. 
I tell myself that I came across that special something with which I'm going to be able to do simple derivations, alignment and resampling.

But I am lost in this world of webpack browserify etc. I did a lot of tests but without success.
Results always happen to : Uncaught ReferenceError: TimeSeries is not defined.
Maybe I'm not on the right track.

My first question: Can Pond be used in a html page as a standard javascript library.
If so, is there somewhere a distribution of the pond.js javascript file ready for use?

Thank you for your help

**Comment by pjm17971** [comment]
Well I think the simple answer is that pond ships only as a module and doesn't expose itself as a global variable. There is very little need for that these days, and there's some questions from our employer about bundling someone else's software (our dependencies) with what we ship. But, we'll keep it in mind when we ship the typescript version (i.e. if it's easy to support, then perhaps) next month.

In the mean time, you probably want to figure out how to use webpack to bundle javascript together that uses module imports. It will make your life a lot easier. Basically you tell webpack the input js file, which itself imports from npm installed modules like pond (or other js files) and it follows the tree down packaging it all in a single javascript bundle (just another js file) that has everything needed to run together. You then import that js bundle into your standard html page. It's not really magic, at least in its simplest form.

I found this useful when I first used webpack:
https://github.com/petehunt/webpack-howto
