### ISSUE TITLE
TypeScript Declarations

### ISSUE THREAD

**Issue by TimMensch** [esnet/pond#86]
I was ecstatic to read that Pond.js was shipping with TypeScript declarations! So I installed Pond.js and tried to get types in TypeScript...no luck.

So then I looked to see what the declaration file looked like, and...no file?

I installed `pondjs` using `yarn add pondjs`, and I got version 0.8.7. Looking in `package.json` I see

```
"types: "lib/entry.d.ts"
```

...as if there's a type file. But no `lib/entry.d.ts`. 

Build problem? Since the docs mentioned "...as of 0.8.6" I tried sync'ing that version, and no luck. There are no declarations there either.

Would love to get a build with actual declarations in it, or even someone putting the file into a gist would be useful. :)

**Comment by TimMensch** [comment]
Found the issue: A bad merge, I'm guessing, in this commit:

https://github.com/esnet/pond/commit/2ec679b697c5718e7ee4bdffc424a029dc4b424c

Regardless, the very next commit after the pull request for the TypeScript declarations nuked them.

**Comment by pjm17971** [comment]
I'll have someone add them back in. The next version of pond.js is written in typescript, so full type safety. The charts code probably won't be updated to use it for a bit though, if you've come to pond via that. Anyway, should be easy enough fix. Thanks for reporting.

**Comment by TimMensch** [comment]
Hey -- I finally started _using_ pond.js with those declarations, and unfortunately they're wrong.

The exported `Pipeline` class is a class, while the actual `Pipeline` export is a factory function for the class. So you can't use any of the samples as-is (they all start with `Pipeline().`, which is a TypeScript error.

**Comment by TimMensch** [comment]
Submitted #90 as a fix.

**Comment by sartaj10** [comment]
Thanks! Merged #90
