### ISSUE TITLE
Merging/filling two columns with irregular event times

### ISSUE THREAD

**Issue by aaronrosenthal** [esnet/pond#88]
Is it possible to merge/fill two time series columns with irregular event times that don't line up? For example, if I change the "can append two timeseries together using merge" test so that the column names are different:

```javascript
const PARTIAL_TRAFFIC_PART_A = {
    name: "star-cr5:to_anl_ip-a_v4",
    columns: ["time", "valueA"],
    points: [[1400425947000, 34], [1400425948000, 13], [1400425949000, 67], [1400425950000, 91]]
};

const PARTIAL_TRAFFIC_PART_B = {
    name: "star-cr5:to_anl_ip-a_v4",
    columns: ["time", "valueB"],
    points: [[1400425951000, 65], [1400425952000, 86], [1400425953000, 27], [1400425954000, 72]]
};

const tile1 = new TimeSeries(PARTIAL_TRAFFIC_PART_A);
const tile2 = new TimeSeries(PARTIAL_TRAFFIC_PART_B);
const trafficSeries = TimeSeries.timeSeriesListMerge({
    name: "traffic",
    source: "router",
    seriesList: [tile1, tile2]
});
```

This causes the points array to only have 2 columns (time and data), even though the columns array has 3 columns (time, valueA, and valueB). Merging only seems to work the way I expect if the timestamps are the same for both series.

**Comment by pjm17971** [comment]
Ok, I took a look at this and it seems to be a serialization bug that I haven't encountered before.

The expected result would be something like this, right?
```
      { name: 'traffic',
        tz: 'Etc/UTC',
        columns: [ 'time', 'valueA', 'valueB' ],
        points:
         [ [ 1400425947000, 34, null ],
           [ 1400425948000, 13, null ],
           [ 1400425949000, 67, null ],
           [ 1400425950000, 91, null ],
           [ 1400425951000, null, 65 ],
           [ 1400425952000, null, 86 ],
           [ 1400425953000, null, 27 ],
           [ 1400425954000, null, 72 ] ] }
```

As it converts the TimeSeries to JSON / string it is assuming that internal events have both fields, which isn't a valid assumption if the TimeSeries was created from a merge like this. The merge itself seems ok.

I have a fix and test in my local typescript version of Pond, but I'll try to back port it in the next couple of days.

**Comment by aaronrosenthal** [comment]
Yes, that is what I would expect the result to be. Does the merge also splice in results if the timeranges of both series intersect but the individual timestamp events aren't the same?

**Comment by pjm17971** [comment]
Yeah, that should work.
