### ISSUE TITLE
Aggregated TimeSeries to a BoxChart....

### ISSUE THREAD

**Issue by tech-a-go-go** [esnet/pond#93]
Hi there,

This question is related to both pondjs and timeseries chart so I'm not sure this is the right place to ask...

```
createBoxChartTimeSeries() {
   const aggregatedTimeSeries = scoreTimeSeries.fixedWindowRollup({
      windowSize: '1m',
      aggregation: {min: {score: min()}, max: {score: max()}}
    });
    // convert all data.  I guess this is wasting time.
    const boxChartEvents = aggregatedTimeSeries.collection().map((e) => {
      return new IndexedEvent(
        e.index(),
        {
          score: [
                e.data().get('min'),
                e.data().get('max')
              ]
        },
        false
      );
    });
    return new TimeSeries({ name:'box chart time series', collection: new Collection(boxChartEvents)});
}
```
I would like to show aggregated data in Box Chart but the box chart doesn't accept the data format created by TimeSeries#fixedWindowRollup( ).
So I iterates all data to convert data by collection().map(...) which I think I'm wasting time...

Is there a way to show without converting data ??

Cheers

**Comment by pjm17971** [comment]
The simplest thing is to have the box chart do it itself:
https://github.com/esnet/react-timeseries-charts/blob/master/src/website/packages/charts/examples/cycling/Index.js#L341

There's basically two ways to feed data into the BoxChart, either bring your own (which is what you're doing above, which is useful in the case of sending the ranges from a server), or to do it client side, in which case the BoxChart can do it internally (and it'll cache).

But I think it would be nice if Pond could generate that format more directly.

**Comment by tech-a-go-go** [comment]
Oh, I didn't know BoxChart can do it internally.

> But I think it would be nice if Pond could generate that format more directly.
I hope so but I'm now satisfied !

Thank you !
