### ISSUE TITLE
Consider default NPM package version

### ISSUE THREAD

**Issue by Eric-Arellano** [esnet/pond#99]
Currently, `npm install pondjs` defaults to v1.0.0alpha, as shown in its [package page](https://www.npmjs.com/package/pondjs). 

However, the README warns this is still in alpha and that it does not work yet with `react-timeseries-charts`. The README also states that you must explicitly install v1.0.0alpha and that the project will default to v0.8.7, even though this is not the case. 

Consider restoring v0.8.7 as the NPM default, or otherwise updating all the documentation (including `react-timeseries-charts`) to explicitly instruct installing v0.8.7 if desired.

--

(By the way, great work with the rewrite! TypeScript was a great way to go.)

**Comment by pjm17971** [comment]
Thanks, this was a publishing mistake. It should be fixed now.
